#!/usr/bin/env python3
"""Resolve the conflicts merge_lane.sh leaves behind when integrating a lane.

Usage: resolve_lane_conflicts.py <lane-branch> [--own-prefix PREFIX ...]

Rules (all hunk-level or three-way; NEVER whole-file --ours/--theirs on a
shared file):
  README.md                        -> theirs (regenerated by finish_merge)
  Makefile                         -> keep both sides of every hunk
  files only the lane touched
  (AA add/add or under --own-prefix) -> theirs
  docs/resident.md, docs/overlays.md -> theirs per hunk when ours is a subset
                                       of the lane's rows (else keep both)
  everything else (symbol_addrs,
  yaml, headers, shared .c)        -> git merge-file against the lane's
                                       merge-base, then keep both on residual
                                       conflicts
Exits nonzero if any conflict marker survives.
"""
import re
import subprocess
import sys

MARK = re.compile(r"<<<<<<< [^\n]*\n(.*?)=======\n(.*?)>>>>>>> [^\n]*\n", re.S)


def git(*a, **k):
    return subprocess.run(["git", *a], capture_output=True, text=True, **k)


def keep_both(text):
    return MARK.sub(lambda m: m.group(1) + m.group(2), text)


def theirs_if_subset(text):
    def fix(m):
        ours, theirs = m.group(1), m.group(2)
        ours_rows = [l for l in ours.splitlines() if l.strip()]
        if all(l in theirs for l in ours_rows):
            return theirs
        return ours + theirs
    return MARK.sub(fix, text)


def main():
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        return 2
    branch = args[0]
    own = []
    i = 1
    while i < len(args):
        if args[i] == "--own-prefix":
            own.append(args[i + 1])
            i += 2
        else:
            i += 1
    base = git("merge-base", "HEAD", branch).stdout.strip()
    status = git("status", "--porcelain").stdout.splitlines()
    conflicted = [(l[:2], l[3:]) for l in status if l[:2] in ("UU", "AA", "AU", "UA", "DU", "UD")]
    for code, path in conflicted:
        if path == "README.md":
            git("checkout", "--theirs", "--", path)
            how = "theirs (regenerated later)"
        elif path == "Makefile":
            text = open(path).read()
            open(path, "w").write(keep_both(text))
            how = "keep both"
        elif path in ("config/overlays.us.json", "config/overlay-donors.us.json",
                      "config/lane-reopen-authorizations.us.json",
                      "overlay_undefined_syms.us.txt", "mk/overlay_aliases.generated.mk"):
            # Generated or JSON artifacts: never merge by hunks (a keep-both
            # hunk duplicated the atlas sha256 key and broke the pin file's
            # JSON). Take the lane's copy; finish_merge regenerates the
            # generated ones and JSON dictionaries are re-unioned by hand.
            git("checkout", "--theirs", "--", path)
            how = "theirs (generated/JSON)"
        elif code == "AA" or any(path.startswith(p) for p in own):
            git("checkout", "--theirs", "--", path)
            how = "theirs (lane-owned)"
        elif path in ("docs/resident.md", "docs/overlays.md"):
            text = open(path).read()
            open(path, "w").write(theirs_if_subset(text))
            how = "theirs per hunk where ours is a subset"
        else:
            ours = git("show", f"HEAD:{path}").stdout
            theirs = git("show", f"{branch}:{path}").stdout
            basetxt = git("show", f"{base}:{path}").stdout
            import tempfile, os
            d = tempfile.mkdtemp()
            po, pb, pt = [os.path.join(d, n) for n in ("ours", "base", "theirs")]
            open(po, "w").write(ours); open(pb, "w").write(basetxt); open(pt, "w").write(theirs)
            subprocess.run(["git", "merge-file", po, pb, pt], capture_output=True)
            merged = open(po).read()
            open(path, "w").write(keep_both(merged))
            how = "three-way merge-file, keep both on residue"
        if "<<<<<<<" in open(path, errors="replace").read():
            print(f"UNRESOLVED {path}")
            return 1
        git("add", "--", path)
        print(f"resolved {path}: {how}")
    left = git("grep", "-l", "^<<<<<<< ", "--", ".").stdout.strip()
    if left:
        print("markers remain:", left)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
